-- Thai Trainer — стартовый контент (публичный, без личных данных).
-- Выполни ПОСЛЕ schema.sql. Женская частица ค่ะ/คะ — мужская подставляется в UI по профилю.
-- Слова из видео (source='video') стартуют скрытыми (hidden=t): всплывают после просмотра ролика.

insert into phrases (ru, th, tr, deck, source, hidden, video_id) values
('В ту сторону (направление)', 'ไปทางนั้น', 'pai thaang-nán', 'base', 'chat', false, null),
('Вон там / вон туда (показываю)', 'ตรงนั้น', 'trong-nán', 'base', 'chat', false, null),
('Вы работаете? / Открыто?', 'เปิดไหมคะ', 'pə̀ət mǎi khá', 'base', 'chat', false, null),
('Как красиво!', 'สวยจังเลยค่ะ', 'sǔai jang ləəi khâ', 'base', 'chat', false, null),
('Как тебя зовут?', 'คุณชื่ออะไรคะ', 'khun chʉ̂ʉ à-rai khá', 'base', 'chat', false, null),
('Красивый / красиво', 'สวยค่ะ', 'sǔai khâ', 'base', 'chat', false, null),
('Мне нравится тайская культура', 'ชอบวัฒนธรรมไทยค่ะ', 'chɔ̂ɔp wát-thá-ná-tham thai khâ', 'base', 'chat', false, null),
('Немного сахара', 'ใส่น้ำตาลนิดหน่อยค่ะ', 'sài nám-taan nít-nòi khâ', 'base', 'chat', false, null),
('Нравится жить здесь', 'ชอบอยู่ที่นี่ค่ะ', 'chɔ̂ɔp yùu thîi-nîi khâ', 'base', 'chat', false, null),
('Прошу / проходите (услышу от них)', 'เชิญค่ะ', 'chəən khâ', 'base', 'chat', false, null),
('Сладкий (утверждение)', 'หวานค่ะ', 'wǎan khâ', 'base', 'chat', false, null),
('Уже закрыто (услышу в ответ)', 'ปิดแล้วค่ะ', 'pìt léeo khâ', 'base', 'chat', false, null),
('Чувствую себя посвежевшей (после сауны/душа)', 'สดชื่นมากค่ะ', 'sòt-chʉ̂ʉn mâak khâ', 'base', 'chat', false, null),
('Я люблю Таиланд', 'รักเมืองไทยค่ะ', 'rák mʉʉang-thai khâ', 'base', 'chat', false, null),
('Я учу тайский язык', 'เรียนภาษาไทยค่ะ', 'rian phaa-sǎa thai khâ', 'base', 'chat', false, null),
('А ты как?', 'แล้วคุณล่ะคะ', 'léeo khun lâ khá', 'base', 'seed', false, null),
('Вот это и вот это', 'ขออันนี้กับอันนี้ค่ะ', 'khǒo an-níi kàp an-níi khâ', 'base', 'seed', false, null),
('Говорите медленнее, пожалуйста', 'พูดช้าๆ หน่อยค่ะ', 'phûut cháa-cháa nòi khâ', 'base', 'seed', false, null),
('Да / Нет', 'ใช่ค่ะ / ไม่ใช่ค่ะ', 'châi khâ / mâi-châi khâ', 'base', 'seed', false, null),
('Здравствуйте / До свидания', 'สวัสดีค่ะ', 'sà-wàt-dii khâ', 'base', 'seed', false, null),
('И ещё вот это', 'แล้วก็อันนี้ค่ะ', 'léeo-kɔ̂ an-níi khâ', 'base', 'seed', false, null),
('Извините / простите', 'ขอโทษค่ะ', 'khɔ̌ɔ-thôot khâ', 'base', 'seed', false, null),
('Как дела?', 'สบายดีไหมคะ', 'sà-baai-dii mǎi khá', 'base', 'seed', false, null),
('Можно / Нельзя', 'ได้ค่ะ / ไม่ได้ค่ะ', 'dâi khâ / mâi dâi khâ', 'base', 'seed', false, null),
('Можно вот это (в меню)', 'ขออันนี้ค่ะ', 'khǒo an-níi khâ', 'base', 'seed', false, null),
('Нет, спасибо', 'ไม่เอาค่ะ ขอบคุณค่ะ', 'mâi ao khâ, khòp-khun khâ', 'base', 'seed', false, null),
('Ничего страшного / всё ок', 'ไม่เป็นไรค่ะ', 'mâi-pen-rai khâ', 'base', 'seed', false, null),
('Откуда ты?', 'มาจากไหนคะ', 'maa-jàak-nǎi khá', 'base', 'seed', false, null),
('Повторите ещё раз', 'พูดอีกทีค่ะ', 'phûut ìik-thii khâ', 'base', 'seed', false, null),
('Позвать официанта/продавца', 'พี่คะ', 'phîi khá', 'base', 'seed', false, null),
('Сколько стоит?', 'เท่าไหร่คะ', 'thâo-rài khá', 'base', 'seed', false, null),
('Спасибо', 'ขอบคุณค่ะ', 'khòp-khun khâ', 'base', 'seed', false, null),
('У вас есть …?', 'มี … ไหมคะ', 'mii … mǎi khá', 'base', 'seed', false, null),
('Удачи! Всего доброго!', 'โชคดีนะคะ', 'chôok-dii ná khá', 'base', 'seed', false, null),
('Хорошо (у меня)', 'สบายดีค่ะ', 'sà-baai-dii khâ', 'base', 'seed', false, null),
('Что это?', 'อันนี้อะไรคะ', 'an-níi à-rai khá', 'base', 'seed', false, null),
('Я возьму вот это', 'เอาอันนี้ค่ะ', 'ao an-níi khâ', 'base', 'seed', false, null),
('Я не понимаю', 'ไม่เข้าใจค่ะ', 'mâi khâo-jai khâ', 'base', 'seed', false, null),
('Я не совсем поняла', 'ไม่ค่อยเข้าใจค่ะ', 'mâi khɔ̂i khâo-jai khâ', 'base', 'seed', false, null),
('Я немного говорю по-тайски', 'พูดไทยได้นิดหน่อยค่ะ', 'phûut thai dâi nít-nòi khâ', 'base', 'seed', false, null),
('…бат, можно? (торг)', '…บาทได้ไหมคะ', '… bàat dâai mǎi khá', 'base', 'video', true, 'Let5JPI2R0I'),
('Без скоростной', 'ไม่ขึ้นทางด่วนค่ะ', 'mâi khʉ̂n thaang-dùan khâ', 'base', 'video', true, 'u4af2z4sPq4'),
('Без счётчика — не поеду', 'ไม่ใช้มิเตอร์ ไม่ไปค่ะ', 'mâi chái mí-təə, mâi pai khâ', 'base', 'video', true, 'u4af2z4sPq4'),
('Без чили', 'ไม่เอาพริกค่ะ', 'mâi ao phrík khâ', 'base', 'video', true, 'vpGdD9fgWsw'),
('Большое спасибо', 'ขอบคุณมากค่ะ', 'khɔ̀ɔp-khun mâak khâ', 'base', 'video', true, 'vpGdD9fgWsw'),
('буду / собираюсь (будущее)', 'จะ', 'jà', 'base', 'video', true, 'fhcDc8Ge1d4'),
('быть голодным', 'หิว', 'hǐu', 'base', 'video', true, 'RJGG9hOJOVo'),
('быть сытым', 'อิ่ม', 'ìm', 'base', 'video', true, 'RJGG9hOJOVo'),
('быть, находиться (где-то) / сейчас', 'อยู่', 'yùu', 'base', 'video', true, 'Y9gUTvhaVLI'),
('быть, являться (кем/чем-то)', 'เป็น', 'pen', 'base', 'video', true, 'Y9gUTvhaVLI'),
('вежливая частица (женская)', 'ค่ะ / คะ', 'khâ / khá', 'base', 'video', true, 'vpGdD9fgWsw'),
('вставать', 'ลุก', 'lúk', 'base', 'video', true, 'RJGG9hOJOVo'),
('вы (вежливо)', 'คุณ', 'khun', 'base', 'video', true, 'Vrgeac31-Cw'),
('где', 'ที่ไหน', 'thîi-nǎi', 'base', 'video', true, 'RSlSpcaq9M0'),
('говорить', 'พูด', 'phûut', 'base', 'video', true, 'RJGG9hOJOVo'),
('Да пойдём же', 'ไปสิ', 'pai sì', 'base', 'video', true, 'DBxro6aGCPk'),
('Давай пойдём', 'ไปเถอะ', 'pai thə̀ə', 'base', 'video', true, 'DBxro6aGCPk'),
('есть, кушать', 'กิน', 'gin', 'base', 'video', true, 'RJGG9hOJOVo'),
('завтра', 'พรุ่งนี้', 'phrûng-níi', 'base', 'video', true, 'fhcDc8Ge1d4'),
('заканчивать (учёбу), выпускаться', 'จบ', 'jòp', 'base', 'video', true, 'RJGG9hOJOVo'),
('Идём! / Пошли (сразу)', 'ไปเลย', 'pai ləəi', 'base', 'video', true, 'DBxro6aGCPk'),
('идти / ехать', 'ไป', 'pai', 'base', 'video', true, 'RJGG9hOJOVo'),
('идти пешком', 'เดิน', 'dəən', 'base', 'video', true, 'RJGG9hOJOVo'),
('каждый день', 'ทุกวัน', 'thúk-wan', 'base', 'video', true, 'fhcDc8Ge1d4'),
('как (каким образом)', 'ยังไง', 'yang-ngai', 'base', 'video', true, 'RSlSpcaq9M0'),
('когда', 'เมื่อไหร่', 'mʉ̂a-rài', 'base', 'video', true, 'RSlSpcaq9M0'),
('конец переулка', 'ท้ายซอย', 'tháai sɔɔi', 'base', 'video', true, 'Let5JPI2R0I'),
('который (какой из)', 'อันไหน', 'an-nǎi', 'base', 'video', true, 'RSlSpcaq9M0'),
('красный', 'สีแดง', 'sǐi-dɛɛng', 'base', 'video', true, 'Y9gUTvhaVLI'),
('кто', 'ใคร', 'khrai', 'base', 'video', true, 'RSlSpcaq9M0'),
('любить', 'รัก', 'rák', 'base', 'video', true, 'RJGG9hOJOVo'),
('машина', 'รถ', 'rót', 'base', 'video', true, 'Y9gUTvhaVLI'),
('младший (обращение)', 'น้อง', 'nɔ́ɔng', 'base', 'video', true, 'Vrgeac31-Cw'),
('Мне до … (место)', 'ไป…ค่ะ', 'pai … khâ', 'base', 'video', true, 'u4af2z4sPq4'),
('молоко', 'นม', 'nom', 'base', 'video', true, 'fhcDc8Ge1d4'),
('мы', 'พวกเรา', 'phûak-rao', 'base', 'video', true, 'Vrgeac31-Cw'),
('начало переулка', 'ต้นซอย', 'dtôn sɔɔi', 'base', 'video', true, 'Let5JPI2R0I'),
('Не спешите', 'ไม่ต้องรีบค่ะ', 'mâi tɔ̂ng rîip khâ', 'base', 'video', true, 'Let5JPI2R0I'),
('нравиться', 'ชอบ', 'chɔ̂ɔp', 'base', 'video', true, 'RJGG9hOJOVo'),
('Ну пойдём же (уговариваю)', 'ไปน่า', 'pai nâa', 'base', 'video', true, 'DBxro6aGCPk'),
('он / она', 'เขา', 'khǎo', 'base', 'video', true, 'Vrgeac31-Cw'),
('Остановите вон там', 'จอดโน่นค่ะ', 'jɔ̀ɔt nôon khâ', 'base', 'video', true, 'Let5JPI2R0I'),
('Остановите здесь', 'จอดตรงนี้ค่ะ', 'jɔ̀ɔt trong-níi khâ', 'base', 'video', true, 'Let5JPI2R0I'),
('Остановите там', 'จอดตรงนั้นค่ะ', 'jɔ̀ɔt trong-nán khâ', 'base', 'video', true, 'Let5JPI2R0I'),
('переулок (сой)', 'ซอย', 'sɔɔi', 'base', 'video', true, 'Let5JPI2R0I'),
('писать', 'เขียน', 'khǐan', 'base', 'video', true, 'RJGG9hOJOVo'),
('пить', 'ดื่ม', 'dʉ̀ʉm', 'base', 'video', true, 'RJGG9hOJOVo'),
('По скоростной, да', 'ขึ้นทางด่วนค่ะ', 'khʉ̂n thaang-dùan khâ', 'base', 'video', true, 'u4af2z4sPq4'),
('По счётчику поедете?', 'ใช้มิเตอร์ไหมคะ', 'chái mí-təə mǎi khá', 'base', 'video', true, 'u4af2z4sPq4'),
('Поедем по скоростной (express)?', 'ขึ้นทางด่วนไหมคะ', 'khʉ̂n thaang-dùan mǎi khá', 'base', 'video', true, 'u4af2z4sPq4'),
('Пойдём (по-дружески)', 'ไปนะ', 'pai ná', 'base', 'video', true, 'DBxro6aGCPk'),
('Пойдём вместе', 'ไปกัน', 'pai gan', 'base', 'video', true, 'DBxro6aGCPk'),
('Пойдёшь? / Идёшь?', 'ไปไหม', 'pai mǎi', 'base', 'video', true, 'DBxro6aGCPk'),
('Помедленнее, можно?', 'ช้าๆ หน่อยได้ไหมคะ', 'cháa-cháa nɔ̀ɔi dâai mǎi khá', 'base', 'video', true, 'Let5JPI2R0I'),
('почему', 'ทำไม', 'tham-mai', 'base', 'video', true, 'RSlSpcaq9M0'),
('Прибавьте кондиционер?', 'เปิดแอร์เพิ่มได้ไหมคะ', 'pə̀ət ɛɛ phə̂əm dâai mǎi khá', 'base', 'video', true, 'u4af2z4sPq4'),
('приходить', 'มา', 'maa', 'base', 'video', true, 'RJGG9hOJOVo'),
('работать', 'ทำงาน', 'tham-ngaan', 'base', 'video', true, 'RJGG9hOJOVo'),
('раньше доводилось (когда-то)', 'เคย', 'khəəi', 'base', 'video', true, 'fhcDc8Ge1d4'),
('сейчас, в процессе (маркер)', 'กำลัง', 'gam-lang', 'base', 'video', true, 'fhcDc8Ge1d4'),
('середина переулка', 'กลางซอย', 'glaang sɔɔi', 'base', 'video', true, 'Let5JPI2R0I'),
('сидеть', 'นั่ง', 'nâng', 'base', 'video', true, 'RJGG9hOJOVo'),
('слушать', 'ฟัง', 'fang', 'base', 'video', true, 'RJGG9hOJOVo'),
('смотреть кино', 'ดูหนัง', 'duu nǎng', 'base', 'video', true, 'RSlSpcaq9M0'),
('спать', 'นอน', 'nɔɔn', 'base', 'video', true, 'RJGG9hOJOVo'),
('старший (обращение)', 'พี่', 'phîi', 'base', 'video', true, 'Vrgeac31-Cw'),
('стоять', 'ยืน', 'yʉʉn', 'base', 'video', true, 'RJGG9hOJOVo'),
('тогда, в тот момент', 'ตอนนั้น', 'dtɔɔn-nán', 'base', 'video', true, 'fhcDc8Ge1d4'),
('ты (близким)', 'เธอ', 'thəə', 'base', 'video', true, 'Vrgeac31-Cw'),
('ты (ласково, у пар)', 'ตัวเอง', 'dtua-eeng', 'base', 'video', true, 'Vrgeac31-Cw'),
('Убавьте кондиционер?', 'ลดแอร์หน่อยได้ไหมคะ', 'lót ɛɛ nɔ̀ɔi dâai mǎi khá', 'base', 'video', true, 'u4af2z4sPq4'),
('уже (сделал(а))', 'แล้ว', 'lɛ́ɛo', 'base', 'video', true, 'fhcDc8Ge1d4'),
('учиться', 'เรียน', 'rian', 'base', 'video', true, 'RJGG9hOJOVo'),
('хотеть спать (сонный)', 'ง่วง', 'ngûang', 'base', 'video', true, 'RJGG9hOJOVo'),
('Хочу пить', 'หิวน้ำค่ะ', 'hǐu náam khâ', 'base', 'video', true, 'vpGdD9fgWsw'),
('чей', 'ของใคร', 'khɔ̌ɔng-khrai', 'base', 'video', true, 'RSlSpcaq9M0'),
('читать', 'อ่าน', 'àan', 'base', 'video', true, 'RJGG9hOJOVo'),
('что', 'อะไร', 'à-rai', 'base', 'video', true, 'RSlSpcaq9M0'),
('я (жен., вежливо)', 'ดิฉัน', 'dì-chǎn', 'base', 'video', true, 'Vrgeac31-Cw'),
('я (жен., неформ.)', 'ฉัน', 'chǎn', 'base', 'video', true, 'Vrgeac31-Cw'),
('я (ласково, у пар)', 'เค้า', 'kháo', 'base', 'video', true, 'Vrgeac31-Cw'),
('я (муж.)', 'ผม', 'phǒm', 'base', 'video', true, 'Vrgeac31-Cw'),
('я (со старшими; ласково «мышка»)', 'หนู', 'nǔu', 'base', 'video', true, 'Vrgeac31-Cw'),
('я / мы (по-дружески)', 'เรา', 'rao', 'base', 'video', true, 'Vrgeac31-Cw'),
('Я голодная (хочу есть)', 'หิวข้าวค่ะ', 'hǐu khâao khâ', 'base', 'video', true, 'vpGdD9fgWsw'),
('Я пошла / мне пора', 'ไปแล้วนะคะ', 'pai lɛ́ɛo ná khá', 'base', 'video', true, 'vpGdD9fgWsw'),
('Большой (размер)', 'ใหญ่', 'yài', 'coffee', 'chat', false, null),
('Зелёный чай', 'ชาเขียว', 'chaa khǐao', 'coffee', 'chat', false, null),
('Маленький (размер)', 'เล็ก', 'lék', 'coffee', 'chat', false, null),
('Можно горячий чай', 'ขอชาร้อนค่ะ', 'khǒo chaa rɔ́ɔn khâ', 'coffee', 'chat', false, null),
('Один большой горячий латте и один маленький (без "кэ̂эу")', 'ขอลาเต้ร้อนใหญ่ กับเล็กค่ะ', 'khǒo laa-têe rɔ́ɔn yài kàp lék khâ', 'coffee', 'chat', false, null),
('Чай', 'ชา', 'chaa', 'coffee', 'chat', false, null),
('Без сахара', 'ไม่ใส่น้ำตาลค่ะ', 'mâi sài nám-taan khâ', 'coffee', 'seed', false, null),
('Буду здесь', 'ทานที่นี่ค่ะ', 'thaan thîi-nîi khâ', 'coffee', 'seed', false, null),
('Горячий / Холодный', 'ร้อน / เย็น', 'rɔ́ɔn / yen', 'coffee', 'seed', false, null),
('Ещё один стакан, пожалуйста', 'ขออีกแก้วค่ะ', 'khǒo ìik kâew khâ', 'coffee', 'seed', false, null),
('Кофе со льдом, пожалуйста', 'ขอกาแฟเย็นค่ะ', 'khǒo kaa-fee yen khâ', 'coffee', 'seed', false, null),
('Латте со льдом, пожалуйста', 'ขอลาเต้เย็นค่ะ', 'khǒo laa-têe yen khâ', 'coffee', 'seed', false, null),
('Менее сладкий', 'หวานน้อยค่ะ', 'wǎan nɔ́i khâ', 'coffee', 'seed', false, null),
('С собой (навынос)', 'เอากลับค่ะ', 'ao klàp khâ', 'coffee', 'seed', false, null),
('Совсем не сладкий', 'ไม่หวานค่ะ', 'mâi wǎan khâ', 'coffee', 'seed', false, null),
('Средний стакан', 'แก้วกลางค่ะ', 'kâew klaang khâ', 'coffee', 'seed', false, null),
('Большой стакан', 'แก้วใหญ่ค่ะ', 'gɛ̂ɛo yài khâ', 'coffee', 'video', true, 'KRdLsDmiUpg'),
('Маленький стакан', 'แก้วเล็กค่ะ', 'gɛ̂ɛo lék khâ', 'coffee', 'video', true, 'KRdLsDmiUpg'),
('Обычная сладость', 'หวานปกติค่ะ', 'wǎan pòk-gà-tì khâ', 'coffee', 'video', true, 'KRdLsDmiUpg'),
('Очень сладко', 'หวานมากค่ะ', 'wǎan mâak khâ', 'coffee', 'video', true, 'KRdLsDmiUpg'),
('Покрепче (крепкий кофе)', 'เข้มๆ ค่ะ', 'khêm-khêm khâ', 'coffee', 'video', true, 'KRdLsDmiUpg'),
('Вот это, одну штуку', 'อันนี้อันเดียวค่ะ', 'an-níi an-diao khâ', 'market', 'seed', false, null),
('Дороговато!', 'แพงจังค่ะ', 'phɛɛng jang khâ', 'market', 'seed', false, null),
('Можно чуть дешевле?', 'ลดหน่อยได้ไหมคะ', 'lót nòi dâi mǎi khá', 'market', 'seed', false, null),
('Один килограмм', 'หนึ่งโลค่ะ', 'nʉ̀ng loo khâ', 'market', 'seed', false, null),
('Полкило', 'ครึ่งโลค่ะ', 'khrʉ̂ng loo khâ', 'market', 'seed', false, null),
('Сколько за кило?', 'โลละเท่าไหร่คะ', 'loo lá thâo-rài khá', 'market', 'seed', false, null),
('Сладкий? (про фрукт)', 'หวานไหมคะ', 'wǎan mǎi khá', 'market', 'seed', false, null),
('Спелый?', 'สุกไหมคะ', 'sùk mǎi khá', 'market', 'seed', false, null),
('Здесь больно', 'เจ็บตรงนี้ค่ะ', 'jèp trong-níi khâ', 'massage', 'seed', false, null),
('Масляный массаж', 'นวดน้ำมันค่ะ', 'nûat nám-man khâ', 'massage', 'seed', false, null),
('Очень приятно / хорошо', 'สบายมากค่ะ', 'sà-baai mâak khâ', 'massage', 'seed', false, null),
('Помягче, пожалуйста', 'เบาๆ หน่อยค่ะ', 'bao-bao nòi khâ', 'massage', 'seed', false, null),
('Посильнее, пожалуйста', 'หนักๆ หน่อยค่ะ', 'nàk-nàk nòi khâ', 'massage', 'seed', false, null),
('Тайский массаж, один час', 'นวดไทยหนึ่งชั่วโมงค่ะ', 'nûat thai nʉ̀ng chûa-moong khâ', 'massage', 'seed', false, null),
('10 000 (новое слово)', 'หมื่น', 'mʉ̀ʉn', 'num', 'chat', false, null),
('100 000 (новое слово)', 'แสน', 'sɛ̌ɛn', 'num', 'chat', false, null),
('11 (искл.: "один"=эт)', 'สิบเอ็ด', 'sìp-èt', 'num', 'chat', false, null),
('12', 'สิบสอง', 'sìp-sɔ̌ɔng', 'num', 'chat', false, null),
('13', 'สิบสาม', 'sìp-sǎam', 'num', 'chat', false, null),
('1', 'หนึ่ง', 'nʉ̀ng', 'num', 'seed', false, null),
('10', 'สิบ', 'sìp', 'num', 'seed', false, null),
('100', 'ร้อย', 'rɔ́ɔi', 'num', 'seed', false, null),
('1000', 'พัน', 'phan', 'num', 'seed', false, null),
('2', 'สอง', 'sɔ̌ɔng', 'num', 'seed', false, null),
('20', 'ยี่สิบ', 'yîi-sìp', 'num', 'seed', false, null),
('21 (искл.: "один" = èt)', 'ยี่สิบเอ็ด', 'yîi-sìp-èt', 'num', 'seed', false, null),
('3', 'สาม', 'sǎam', 'num', 'seed', false, null),
('30', 'สามสิบ', 'sǎam-sìp', 'num', 'seed', false, null),
('4', 'สี่', 'sìi', 'num', 'seed', false, null),
('40', 'สี่สิบ', 'sìi-sìp', 'num', 'seed', false, null),
('5', 'ห้า', 'hâa', 'num', 'seed', false, null),
('50', 'ห้าสิบ', 'hâa-sìp', 'num', 'seed', false, null),
('6', 'หก', 'hòk', 'num', 'seed', false, null),
('60', 'หกสิบ', 'hòk-sìp', 'num', 'seed', false, null),
('7', 'เจ็ด', 'jèt', 'num', 'seed', false, null),
('70', 'เจ็ดสิบ', 'jèt-sìp', 'num', 'seed', false, null),
('8', 'แปด', 'pàet', 'num', 'seed', false, null),
('80', 'แปดสิบ', 'pàet-sìp', 'num', 'seed', false, null),
('9', 'เก้า', 'kâao', 'num', 'seed', false, null),
('90', 'เก้าสิบ', 'kâao-sìp', 'num', 'seed', false, null),
('миллион', 'ล้าน', 'láan', 'num', 'video', true, 'FSZFYNNYh38'),
('Жареный рис с курицей', 'ข้าวผัดไก่ค่ะ', 'khâao-phàt-kài khâ', 'resto', 'chat', false, null),
('Курица', 'ไก่', 'kài', 'resto', 'chat', false, null),
('Можно два вот этих (любое блюдо)', 'ขออันนี้สองที่ค่ะ', 'khǒo an-níi sɔ̌ɔng thîi khâ', 'resto', 'chat', false, null),
('Можно два супа', 'ขอซุปสองถ้วยค่ะ', 'khǒo súp sɔ̌ɔng thûai khâ', 'resto', 'chat', false, null),
('Можно суп, пожалуйста', 'ขอซุปค่ะ', 'khǒo súp khâ', 'resto', 'chat', false, null),
('Рис / еда', 'ข้าว', 'khâao', 'resto', 'chat', false, null),
('Вкусно', 'อร่อยค่ะ', 'à-ròi khâ', 'resto', 'seed', false, null),
('Ещё 5 минут, пожалуйста', 'ขออีกห้านาทีค่ะ', 'khǒo ìik hâa naa-thii khâ', 'resto', 'seed', false, null),
('Можно воды (простой)', 'ขอน้ำเปล่าค่ะ', 'khǒo nám-plàao khâ', 'resto', 'seed', false, null),
('Можно ещё одно', 'ขออีกอันค่ะ', 'khǒo ìik an khâ', 'resto', 'seed', false, null),
('Можно ложку и вилку', 'ขอช้อนส้อมค่ะ', 'khǒo chɔ́ɔn-sɔ̂ɔm khâ', 'resto', 'seed', false, null),
('Можно меню, пожалуйста', 'ขอเมนูหน่อยค่ะ', 'khǒo mee-nuu nòi khâ', 'resto', 'seed', false, null),
('Можно счёт, пожалуйста', 'ขอบิลค่ะ', 'khǒo bin khâ', 'resto', 'seed', false, null),
('Не остро, пожалуйста', 'ไม่เผ็ดค่ะ', 'mâi phèt khâ', 'resto', 'seed', false, null),
('Очень вкусно!', 'อร่อยมากค่ะ', 'à-ròi mâak khâ', 'resto', 'seed', false, null),
('Подождите минутку', 'รอแป๊บนึงนะคะ', 'rɔɔ pɛ́p-nʉng ná khá', 'resto', 'seed', false, null),
('Сначала посмотрю меню', 'ขอดูเมนูก่อนค่ะ', 'khǒo duu mee-nuu kɔ̀ɔn khâ', 'resto', 'seed', false, null),
('Счёт, пожалуйста', 'เช็คบิลค่ะ', 'chék-bin khâ', 'resto', 'seed', false, null),
('Что посоветуете?', 'แนะนำอะไรดีคะ', 'nɛ́-nam à-rai dii khá', 'resto', 'seed', false, null),
('Чуть-чуть остро', 'เผ็ดนิดหน่อยค่ะ', 'phèt nít-nòi khâ', 'resto', 'seed', false, null),
('Это острое?', 'อันนี้เผ็ดไหมคะ', 'an-níi phèt mǎi khá', 'resto', 'seed', false, null),
('Без овощей', 'ไม่เอาผักค่ะ', 'mâi ao phàk khâ', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Добавьте мяса, пожалуйста', 'ขอเนื้อเพิ่มค่ะ', 'khɔ̌ɔ nʉ́a phə̂əm khâ', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Долго ждать?', 'รอนานไหมคะ', 'rɔɔ naan mǎi khá', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('И яйцо тоже', 'เอาไข่ด้วยค่ะ', 'ao khài dûai khâ', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Можно ещё риса?', 'ขอข้าวเพิ่มได้ไหมคะ', 'khɔ̌ɔ khâao phə̂əm dâai mǎi khá', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Немного чили', 'ใส่พริกนิดเดียวค่ะ', 'sài phrík nít-dieow khâ', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Поострее, пожалуйста', 'เอาเผ็ดๆ ค่ะ', 'ao phèt-phèt khâ', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Сколько за коробку?', 'กล่องละเท่าไหร่คะ', 'glɔ̀ng lá thâo-rài khá', 'resto', 'video', true, 'nBeMnQZ_Knk'),
('Где находится …?', '… อยู่ไหนคะ', '… yùu nǎi khá', 'shop', 'seed', false, null),
('Можно оплатить картой?', 'จ่ายบัตรได้ไหมคะ', 'jàai bàt dâi mǎi khá', 'shop', 'seed', false, null),
('Оплачу QR-кодом', 'สแกนจ่ายค่ะ', 'sà-kɛɛn jàai khâ', 'shop', 'seed', false, null),
('Пакет не нужен', 'ไม่เอาถุงค่ะ', 'mâi ao thǔng khâ', 'shop', 'seed', false, null),
('Подогревать не нужно', 'ไม่อุ่นค่ะ', 'mâi ùn khâ', 'shop', 'seed', false, null),
('Подогрейте, пожалуйста', 'อุ่นด้วยค่ะ', 'ùn dûai khâ', 'shop', 'seed', false, null),
('Только это (это всё)', 'แค่นี้ค่ะ', 'khɛ̂ɛ níi khâ', 'shop', 'seed', false, null);
